name: CI-CD  # Название workflow (отображается в GitHub Actions)

on:
  push:
    branches: [main]  # Запускается только при push в ветку main

# Глобальные переменные окружения, применяются во всех jobs
env:
  APP_IMAGE_NAME: myapp              # Название образа
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: kubsu
  DB_USER: kubsu
  DB_PASS: kubsu

jobs:
  # 🛠 Сборка Docker-образа (builder-stage)
  build:
    runs-on: self-hosted             # Запуск job на локальном runner
    outputs:                         # Выходные данные — передаются в другие jobs
      image-tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка тега из SHA коммита
        id: set-tag
        run: echo "tag=${{ env.APP_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Сборка builder-образа для тестов
        run: docker build --target builder -t ${{ steps.set-tag.outputs.tag }} .

  # ✅ Тестирование приложения в builder-контейнере
  test:
    runs-on: self-hosted
    needs: build                    # Запускается только после завершения build

    services:                       # Вспомогательные сервисы, например PostgreSQL
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - ${{ env.DB_PORT }}:${{ env.DB_PORT }}
        options: >-
          --health-cmd "pg_isready -U ${{ env.DB_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Клонирование кода
        uses: actions/checkout@v3

      - name: Ожидание готовности PostgreSQL
        run: |
          until pg_isready -h ${{ env.DB_HOST }} -p ${{ env.DB_PORT }} -U ${{ env.DB_USER }}; do
            echo "⏳ Waiting for Postgres..."
            sleep 2
          done

      - name: Запуск тестов
        run: |
          docker run --rm \
            --network host \
            -e PYTHONPATH=/app \
            -e DB_HOST=${{ env.DB_HOST }} \
            -e DB_PORT=${{ env.DB_PORT }} \
            -e DB_NAME=${{ env.DB_NAME }} \
            -e DB_USER=${{ env.DB_USER }} \
            -e DB_PASS=${{ env.DB_PASS }} \
            ${{ needs.build.outputs.image-tag }} \
            pytest tests

  # 🚀 Деплой приложения на удалённый сервер
  deploy:
    runs-on: self-hosted
    needs: [build, test]           # Запускается только если build и test успешны

    steps:
      - name: Клонирование кода
        uses: actions/checkout@v3

      - name: Настройка SSH-агента
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Сборка финального production-образа
        run: docker build -t ${{ env.APP_IMAGE_NAME }}:final .

      - name: Деплой на сервер
        run: |
          echo "🚀 Загружаем образ на сервер и перезапускаем контейнер..."

          # Отправляем Docker-образ по SSH на сервер
          docker save ${{ env.APP_IMAGE_NAME }}:final | ssh -o StrictHostKeyChecking=no \
            -p ${{ secrets.PORT }} \
            ${{ secrets.USER }}@${{ secrets.HOST }} \
            "podman load && podman tag ${{ env.APP_IMAGE_NAME }}:final ${{ env.APP_IMAGE_NAME }}:final"

          # Перезапускаем контейнер на удалённой машине
          ssh -o StrictHostKeyChecking=no \
            -p ${{ secrets.PORT }} \
            ${{ secrets.USER }}@${{ secrets.HOST }} \
            "podman stop ${{ env.APP_IMAGE_NAME }} || true && \
             podman rm ${{ env.APP_IMAGE_NAME }} || true && \
             podman run -d --name ${{ env.APP_IMAGE_NAME }} \
             --network=host \
             ${{ env.APP_IMAGE_NAME }}:final"
